# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy.js CI

on:
  push:
    branches:
      - master

jobs:
  cancel:
    name: 'Cancel Previous Runs'
    runs-on: self-hosted
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          workflow_id: 22152243
          access_token: ${{ github.token }}
  notify:
    needs: cancel
    name: CD Pipeline
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm i
      - run: ng build
      - run: cd dist\angular-starter
      - run: ng serve
    env:
      CI: true
